[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "dwarf hungry sick release master artefact make animal loop street vault veteran patch rate else update tomato scrub action feed shell balcony suit glad"
